#ifndef FJIFFYLDG_H
#define FJIFFYLDG_H

/* Generated with cbindgen:0.29.3 */

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#ifdef FJIFFYLDG_SHARED
#if defined(_WIN32) || defined(__CYGWIN__)
#if defined(BUILDING_FJIFFYLDG)
#define FJIFFYLDG_API __declspec(dllexport)
#else
#define FJIFFYLDG_API __declspec(dllimport)
#endif
#elif defined(__GNUC__) || defined(__clang__)
#define FJIFFYLDG_API __attribute__((visibility("default")))
#else
#define FJIFFYLDG_API
#endif
#else
#define FJIFFYLDG_API
#endif

/** UTF encoding mode for RestartScanFile. */
enum FjiffyldgUtfMode {
    FJIFFYLDG_UTF_DEFAULT    =  0,
    FJIFFYLDG_UTF16_LE       =  1,
    FJIFFYLDG_UTF16_BE       =  2,
    FJIFFYLDG_UTF32_LE       =  3,
    FJIFFYLDG_UTF32_BE       =  4,
    FJIFFYLDG_UTF_AUTO       = -1
};


/**
 * C ABI 使用的不透明文件处理句柄。
 */
typedef struct fjiffyldg_t fjiffyldg_t;

/**
 * C ABI 句柄指针类型。
 */
typedef struct fjiffyldg_t *fjiffyldg_ptr;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * 创建并返回一个 `fjiffyldg` 文件处理句柄。
 */
FJIFFYLDG_API fjiffyldg_ptr fjiffyldg_create(void);

/**
 * 释放 `fjiffyldg` 文件处理句柄。
 */
FJIFFYLDG_API void fjiffyldg_clear(fjiffyldg_ptr fm);

/**
 * 加载文件并启动后台行扫描。
 */
FJIFFYLDG_API int LoadAndScanFile(fjiffyldg_ptr fm, const char *name);

/**
 * 仅加载文件，不启动行扫描。
 */
FJIFFYLDG_API int LoadFileOnly(fjiffyldg_ptr fm, const char *name);

/**
 * 获取文件加载状态。
 */
FJIFFYLDG_API int GetFileIsLoaded(fjiffyldg_ptr fm);

/**
 * 重新扫描已加载文件的行结构。
 * 重新扫描已加载文件的行结构。
 *
 * @return 0 if successful, non-zero error code on failure.
 */
FJIFFYLDG_API int RestartScanFile(fjiffyldg_ptr fm, const char *name, long long offset, int utf);

/**
 * 阻塞等待后台行扫描完成。
 */
FJIFFYLDG_API void WaitFileScanTaskFinished(fjiffyldg_ptr fm);

/**
 * 请求停止后台行扫描并清空当前行索引。
 */
FJIFFYLDG_API void BackstageRequestStop(fjiffyldg_ptr fm);

/**
 * 获取文件行数。
 */
FJIFFYLDG_API long long GetFileLineCount(fjiffyldg_ptr fm);

/**
 * 获取指定行的起始字节位置。
 */
FJIFFYLDG_API long long GetFileLinePos(fjiffyldg_ptr fm, long long index);

/**
 * 获取指定行的内容长度。
 */
FJIFFYLDG_API long long GetFileLineLength(fjiffyldg_ptr fm, long long index);

/**
 * 根据字节位置查找所在行索引。
 */
FJIFFYLDG_API long long GetFileLineIndex(fjiffyldg_ptr fm, long long pos);

/**
 * 从指定字节位置读取文件数据。
 */
FJIFFYLDG_API const char *ReadFileData(fjiffyldg_ptr fm, long long pos, unsigned int *len);

/**
 * 按行边界读取文件数据，并截断超长行。
 */
FJIFFYLDG_API
const char *ReadFileDataLLineCut(fjiffyldg_ptr fm,
                                 long long *index,
                                 long long *bpos,
                                 long long *epos,
                                 unsigned int *len);

/**
 * 从指定位置读取到当前行末尾。
 */
FJIFFYLDG_API
const char *ReadFileDataEndOfLine(fjiffyldg_ptr fm,
                                  long long index,
                                  long long pos,
                                  unsigned int *len);

/**
 * 获取由句柄持有的整个文件 mmap 指针。
 */
FJIFFYLDG_API
const char *GetFileMappedHuge(fjiffyldg_ptr fm,
                              const char *fileName,
                              long long *bufferSize);

/**
 * 清理 huge mmap 内部映射资源。
 */
FJIFFYLDG_API void ClearHugeBuffer(fjiffyldg_ptr fm);

/**
 * 获取文件大小。
 */
FJIFFYLDG_API long long GetFileSizeByteCount(const char *name);

/**
 * 检查文本是否全部为 ASCII。
 */
FJIFFYLDG_API unsigned int CheckTextASCII(const char *text, unsigned int len);

/**
 * 检查完整文本是否为 UTF-8。
 */
FJIFFYLDG_API unsigned int CheckWholeTextUtf8(const char *text, unsigned int len);

/**
 * 随机抽样检查文本片段是否为 UTF-8。
 */
FJIFFYLDG_API unsigned int CheckExtractTextUtf8(const char *text, unsigned int len);

/**
 * 统计 UTF-8 字符数，并推进调用方传入的文本指针。
 */
FJIFFYLDG_API unsigned int GetUtf8TextCharCount(const char **text, unsigned int len);

/**
 * 克隆文件。
 */
FJIFFYLDG_API int ToCloneFile(const char *oldFileName, const char *newFileName);

/**
 * 保存指定内容到文件。
 */
FJIFFYLDG_API int ToSaveFile(const char *fileName, const char *buffer, long long len);

/**
 * 追加指定内容到文件。
 */
FJIFFYLDG_API int ToAppendFile(const char *fileName, const char *buffer, long long len);

/**
 * 将第二个文件内容追加到第一个文件。
 */
FJIFFYLDG_API int ToConcatenateFile(const char *catFileName, const char *appendFileName);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FJIFFYLDG_H */

#ifdef __cplusplus
#ifndef FJIFFYLDG_CPP_WRAPPER_H
#define FJIFFYLDG_CPP_WRAPPER_H
namespace Fjiffyldg {
class Fjiffyldg {
public:
    Fjiffyldg() : handle_(fjiffyldg_create()) {}

    Fjiffyldg(Fjiffyldg &&other) noexcept : handle_(other.handle_) { other.handle_ = nullptr; }

    Fjiffyldg &operator=(Fjiffyldg &&other) noexcept {
        if (this != &other) {
            fjiffyldg_clear(handle_);
            handle_ = other.handle_;
            other.handle_ = nullptr;
        }
        return *this;
    }

    Fjiffyldg(const Fjiffyldg &) = delete;
    Fjiffyldg &operator=(const Fjiffyldg &) = delete;

    ~Fjiffyldg() { fjiffyldg_clear(handle_); }

    fjiffyldg_ptr GetFjiffyldgHandle() { return handle_; }

private:
    fjiffyldg_ptr handle_;
};
}
#endif
#endif
